### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by xiaoMing8** [AndroidCoderPeng/AutoDingding#9]
![image](https://user-images.githubusercontent.com/33375536/109470616-a4a15e80-7aaa-11eb-9cd0-7547d3a8804e.png)

**Comment by AndroidCoderPeng** [comment]
自行编译一下就好了，同步下Gradle



---原始邮件---
发件人: "xiaoMing"<notifications@github.com&gt;
发送时间: 2021年3月1日(周一) 下午4:25
收件人: "AndroidCoderPeng/AutoDingding"<AutoDingding@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [AndroidCoderPeng/AutoDingding] 项目报错 (#9)

**Comment by xiaoMing8** [comment]
不行，是as版本问题么

**Comment by xiaoMing8** [comment]
![image](https://user-images.githubusercontent.com/33375536/109578995-1d4bfd80-7b33-11eb-9725-feffdbf2ad53.png)
![image](https://user-images.githubusercontent.com/33375536/109579012-2341de80-7b33-11eb-8974-e3dbb8315c1b.png)

这几个按钮我都点了，还是不行，我是小白

**Comment by xiaoMing8** [comment]
![image](https://user-images.githubusercontent.com/33375536/109579429-d4487900-7b33-11eb-9b21-fc86b4d14fc2.png)
![image](https://user-images.githubusercontent.com/33375536/109579450-dad6f080-7b33-11eb-845c-a7c653fcef26.png)

update 也不行

**Comment by AndroidCoderPeng** [comment]
加我QQ 290677893



---原始邮件---
发件人: "xiaoMing"<notifications@github.com&gt;
发送时间: 2021年3月2日(周二) 上午8:47
收件人: "AndroidCoderPeng/AutoDingding"<AutoDingding@noreply.github.com&gt;;
抄送: "I‘m a Coder"<290677893@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [AndroidCoderPeng/AutoDingding] 项目报错 (#9)




 

 
 
update 也不行
